package net.darkhax.aem;

import java.util.Arrays;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.darkhax.aem.common.ProxyCommon;
import net.darkhax.aem.handler.ConfigurationHandler;
import net.darkhax.aem.handler.EnchantmentListExpansionHandler;
import net.darkhax.aem.util.Constants;

@Mod(modid = Constants.MOD_ID, name = Constants.MOD_NAME, version = Constants.VERSION_NUMBER)
public class AdditionalEnchantments {
    
    @SidedProxy(clientSide = Constants.CLIENT_PROXY_CLASS, serverSide = Constants.SERVER_PROXY_CLASS)
    public static ProxyCommon proxy;
    
    @Mod.Instance(Constants.MOD_ID)
    public static AdditionalEnchantments instance;
    
    public static ConfigurationHandler cfg = null;
    
    @EventHandler
    public void preInit (FMLPreInitializationEvent pre) {
        
        setModInfo(pre.getModMetadata());
        proxy.registerSidedEvents();
        cfg = new ConfigurationHandler(pre.getSuggestedConfigurationFile());
        new EnchantmentListExpansionHandler();
        new Enchantments();
        cfg.syncConfigData();
    }
    
    /**
     * A simple method which can be used to print debug messages. This method checks with the
     * configuration file to ensure that outputs to the log have been enabled.
     * 
     * @param message
     */
    public static void printDebugMessage (String message) {
        
        if (ConfigurationHandler.allowDebug)
            Constants.LOGGER.info(message);
    }
    
    void setModInfo (ModMetadata meta) {
        
        meta.authorList = Arrays.asList("Darkhax");
        meta.logoFile = "";
        meta.credits = "Maintained by Darkhax";
        meta.description = "";
        meta.url = "http://darkhax.net";
        meta.autogenerated = false;
    }
}